name: tests
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-11-arm
            msys_prefix: mingw-w64-clang-aarch64
            msys_system: CLANGARM64
          - os: windows-latest
            msys_prefix: mingw-w64-x86_64
            msys_system: MINGW64
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          install: base-devel openssl-devel ${{ matrix.msys_prefix }}-cc ${{ matrix.msys_prefix }}-gperf ${{ matrix.msys_prefix }}-nasm
          msystem: ${{ matrix.msys_system }}
